### ISSUE TITLE
install failed?

### ISSUE THREAD

**Issue by beanumber** [Amherst-Statistics/CollegeScorecard#1]
```
> devtools::install_github("Amherst-Statistics/CollegeScorecard")
Downloading GitHub repo Amherst-Statistics/CollegeScorecard@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/Amherst-Statistics/CollegeScorecard/tarball/HEAD' failed
```
Am I doing something wrong here?

**Comment by beanumber** [comment]
I think this is just timing out. Unfortunately downloading the repo comes as a ZIP file, which can't be installed as a package on Linux. 

Is the only way to install this package to clone the repo and build it locally??

**Comment by nicholasjhorton** [comment]
Sorry to hear about the problems. I've not experienced these but will investigate.

**Comment by nicholasjhorton** [comment]
I'm sorry to hear about the problems.

I was able to install this on our server (running R 4.1.0). Are you still seeing these issues?

**Comment by beanumber** [comment]
I was able to get the package installed by cloning the repo and building locally.

**Comment by nicholasjhorton** [comment]
Sorry for the complications on this front. I don't know if there's something I can do to assist.
